### ISSUE TITLE
Cannot get req.url

### ISSUE THREAD

**Issue by eduarddotgg** [alessioalex/inject-html#1]
Could you please help me to figure out what can be the problem?

var mimeType = mime.lookup(req.url);
                              ^
TypeError: Cannot read property 'url' of undefined

app.listen(port, function(res, req){
 inject(req, res, function() {
    res.setHeader('Content-Type', 'text/html');
    if (req.url === '/') {
      fs.createReadStream.pipe(res);
    } else {
      res.statusCode = 404;
      res.end('Page Not Found');
    }
  });
});

Actually i would like to inject html to every page while server runs, so it wasn't directly in the file and when compiling to html with gulp or grunt there was no injected html.

**Comment by alessioalex** [comment]
Hey there, can you provide me a snippet with what you are trying to do? It's hard to determine what gone wrong without a snippet.

The example above seems to be from the repo. How exactly are you using that? / @admdh

**Comment by eduarddotgg** [comment]
``` js
'use strict';

// Variables
var express = require('express');
var app = express();
var http = require('http');
var routes = require('./bin/routes/routes');
var harp = require('harp');
var jade = require('jade');
var cl = require('colors');
var injectCode = require('inject-html');

var open = require('open');

var pjson = require('./package.json');

var pref = "http://"
var host = pjson.host || "localhost";
var port = pjson.port || 8000;

var webRootPath = "/webroot";

// View engine
app.set('views', __dirname + webRootPath);
app.set('view engine', 'jade');

// Routes
app.get('./', routes.index);

// Harp
app.use(express.static(__dirname + webRootPath));
app.use(harp.mount(__dirname + webRootPath));

var inject = injectCode({
  // type: 'append', // default 'prepend'
  code: "<script>alert('injected!!')</script>" // HTML code
});

// APP listen port
app.listen(port, function(res, req){
    inject(req, res, function() {
        res.setHeader('Content-Type', 'text/html');

        if (req.url === '/') {
            fs.createReadStream.pipe(res);
        } else {
            res.statusCode = 404;
            res.end('Page Not Found\n');
        }
    });
});
```

**Comment by alessioalex** [comment]
I've modified your example and it should work now. Try this out:

``` js
'use strict';

// Variables
var express = require('express');
var app = express();
var http = require('http');
var routes = require('./bin/routes/routes');
var harp = require('harp');
var jade = require('jade');
var cl = require('colors');
var injectCode = require('inject-html');

var open = require('open');

var pjson = require('./package.json');

var pref = "http://"
var host = pjson.host || "localhost";
var port = pjson.port || 8000;

var webRootPath = "/webroot";

// View engine
app.set('views', __dirname + webRootPath);
app.set('view engine', 'jade');


var inject = injectCode({
  // type: 'append', // default 'prepend'
  code: "<script>alert('injected!!')</script>" // HTML code
});
// loading inject middleware before everything else
app.use(inject);

// Routes
app.get('./', routes.index);

// Harp
app.use(express.static(__dirname + webRootPath));
app.use(harp.mount(__dirname + webRootPath));

// APP listen port
app.listen(port);
```

**Comment by eduarddotgg** [comment]
Thank you! it works.
i have one more question. is there a way to add inject variable that was created in server file?
so injection could be something like this:

``` js
var inject = injectCode({
  code: someVariableGoesHere
});
```

**Comment by alessioalex** [comment]
@admdh you can put whatever HTML code you want in there, it's fine.

**Comment by eduarddotgg** [comment]
i have some variable that is generated with node.js(directly in app.js or server.js) and i would like to inject it with some html.
for example:
var number = 500
var inject = injectCode(
code: number
});

or generate json object there.
and is it possible to inject multiple times?

**Comment by alessioalex** [comment]
Yes you can do that, for example:

``` js
var number = 500;

var inject = injectCode({
  code: '<script>window.myApp = { number: ' + number + ' }; </script>'
});
```

**Comment by eduarddotgg** [comment]
Thank you for your help!

**Comment by alessioalex** [comment]
Anytime, glad to help!
