### ISSUE TITLE
Reduce amount of dependencies

### ISSUE THREAD

**Issue by frenzzy** [alessioalex/inject-html#6]
Hi @alessioalex! Thank you for the incredible work with `inject-html`.

I have a little suggestion, could we reduce amount of dependencies? It feels like the feature could be implemented without any dependencies at all and without a significant source code lines increase. What do you think?

For example [BundlePhobia](https://bundlephobia.com/result?p=inject-html) says that `mime-db` module is in 65 times larger in size than `inject-html` but you are not actually using it.

<img width="1154" alt="Dependencies" src="https://user-images.githubusercontent.com/640669/66199194-caa0b480-e6a6-11e9-8736-97ea4141e129.png">

**Comment by alessioalex** [comment]
Hi @frenzzy !

I'm not exactly sure how this module would work without any dependency at all? I'm actually using all of them. For example that `mime-db` is used by a module that's detecting whether the response is an `html` page or not: https://github.com/alessioalex/inject-html/blob/78dbbb6b79129aad445df603c17b65ba68b51289/index.js#L21,L24

**Comment by frenzzy** [comment]
Thank you for your response. It seems that I did not carefully look at the source code, but you're right, sorry. I understand that rewriting code without using dependencies (or using them as less as possible) is a time consuming process and adds a little profit for most devs. I am just a guy who likes minimalism - less dependencies, faster to download, executes faster, better security, no dependency deprecation warning, less compatibility problems etc. ;)

I am closing this for now, thanks again for your time. Have a good day!

PS.: I found an [alternative](https://github.com/daffl/connect-injector) which in [8 times smaller](https://bundlephobia.com/result?p=connect-injector) and looks more flexible.

**Comment by alessioalex** [comment]
I like minimalism as well, but writing a streamable http `gzip` module, mime-type detection library and html streaming parser is outside of the scope of the module.

Thank you for the alternative! There are however big differences between the two libraries:

- `inject-html` is compatible with any Node.js framework or none at all
- `inject-html` is not buffering content in memory, but uses the streaming parser to detect where it should inject the content (so the 'executes faster' alternative would most likely be false in scenarios where you have more content to send the client)
- `inject-html` will detect HTML responses automatically and inject your content without you manually having to detect them
- `inject-html` automatically does `gzip` decompression for you if needed and removes the `Content-Length` header (which is necessary when you inject content and thus modify the content size)

May I ask about your interest in having the library smaller btw? Are you trying to include it in a SSR app?
